### ISSUE TITLE
PF

### ISSUE THREAD

**Issue by jmontes50** [Kav02/DEV013-text-analyzer#1]
Usar una etiqueta main
Ejecutar JS al finalizar el html, justo antes del body
Las variables van super!, solo bsuca elegir entre Inglés o español :D

Sigue comentando tu código se aprende un montón!!

https://htmlreference.io/
https://cssreference.io/
//Box Model!
https://www.freecodecamp.org/news/css-box-model-explained-with-examples/
//un montón de JS!
https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/
//configurar Eslint y Prettier
https://www.redocs.dev/

**Comment by Kav02** [comment]
Listo. Muchas gracias!
